-- ============================================================
-- MIGRACIÓN: permitir que un usuario tenga 2 accesos activos a la
-- vez (Mundial + MLB), cada uno en su propia fila de `entitlements`.
--
-- Cómo correrlo:
-- 1. Entra a supabase.com → tu proyecto → SQL Editor
-- 2. Pega TODO este archivo y dale "Run"
-- 3. Solo se corre UNA vez.
-- ============================================================

-- 1. Agregar la columna product (si no existe)
alter table entitlements add column if not exists product text;

-- 2. Rellenar product para las filas que ya existen
update entitlements
set product = case when plan like 'mlb_%' then 'mlb' else 'mundial' end
where product is null;

-- 3. Hacerla obligatoria de ahora en adelante
alter table entitlements alter column product set not null;

-- 4. Asegurar que la tabla tenga su propia llave primaria (por si
--    user_id era la PK, hace falta una para no perderla al soltarla)
alter table entitlements add column if not exists id bigint generated by default as identity;

-- 5. Quitar la restricción única/PK que había SOLO sobre user_id
--    (busca automáticamente el nombre real de esa restricción)
do $$
declare
  con_name text;
begin
  select conname into con_name
  from pg_constraint
  where conrelid = 'entitlements'::regclass
    and contype in ('p','u')
    and array_length(conkey,1) = 1
    and conkey[1] = (
      select attnum from pg_attribute
      where attrelid = 'entitlements'::regclass and attname = 'user_id'
    );
  if con_name is not null then
    execute format('alter table entitlements drop constraint %I', con_name);
  end if;
end $$;

-- 6. Si la tabla se quedó sin llave primaria, ponerle una sobre id
do $$
begin
  if not exists (select 1 from pg_constraint where conrelid = 'entitlements'::regclass and contype = 'p') then
    execute 'alter table entitlements add primary key (id)';
  end if;
end $$;

-- 7. Nueva restricción: una fila por usuario Y producto
--    (esto es lo que permite tener Mundial + MLB al mismo tiempo)
alter table entitlements add constraint entitlements_user_id_product_key unique (user_id, product);

-- ============================================================
-- Verificación rápida (opcional): debe mostrar 1 fila por
-- combinación user_id + product, sin duplicados.
-- select user_id, product, plan, active from entitlements order by user_id;
-- ============================================================
